### ISSUE TITLE
TomcatEchoTypeB-全版本.jsp

### ISSUE THREAD

**Issue by SummerSec** [feihong-cs/deserizationEcho#1]
java.lang.IllegalArgumentException: Can not set javax.management.MBeanServer field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor to org.apache.tomcat.util.modeler.NoDescriptorRegistry$NoJmxMBeanServer
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:1.8.0_101]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:1.8.0_101]
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[na:1.8.0_101]
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[na:1.8.0_101]

本地测试的时候报错，没成功
另一个版本成功了，师傅知道是什么原因吗？
tomcat版本为9

**Comment by workcha** [comment]
看你的报错好像是MBeanServer对象或者下面的mbsInterceptor没有获取到。我这边没有tomcat9的环境，你可以尝试在idea中断点，然后在Evaluate执行下面代码看看对象是否存在
MBeanServer对象:
org.apache.tomcat.util.modeler.Registry.getRegistry((Object)null, (Object)null).getMBeanServer();
mbsInterceptor对象：
org.apache.tomcat.util.modeler.Registry.getRegistry((Object)null, (Object)null).getMBeanServer().mbsInterceptor
下面是我在tomcat8.x执行的结果
![image](https://user-images.githubusercontent.com/39899007/156684447-48d1e002-fdd1-4cc6-b210-26d957a79402.png)
